name: build_config
version: 1.0.1-dev
description: Support for parsing `build.yaml` configuration.
repository: https://github.com/dart-lang/build/tree/master/build_config

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  checked_yaml: ^2.0.0
  json_annotation: ^4.3.0
  path: ^1.8.0
  pubspec_parse: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.0
  json_serializable: ^6.0.0
  term_glyph: ^1.2.0
  test: ^1.16.0
