name: build_config
version: 0.2.4-dev
description: Support for parsing `build.yaml` configuration.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_config

environment:
  sdk: '>=1.22.1 <2.0.0'

dependencies:
  build: ">=0.11.2 <0.13.0"
  meta: ^1.1.0
  path: ^1.4.0
  yaml: ^2.1.11

dev_dependencies:
  test: ^0.12.24

dependency_overrides:
  build:
    path: ../build
