name: build_config
version: 1.1.2
description: >-
  Format definition and support for parsing `build.yaml` configuration.
repository: https://github.com/dart-lang/build/tree/master/build_config
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  checked_yaml: ^2.0.0
  json_annotation: ^4.8.0
  path: ^1.8.0
  pubspec_parse: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  term_glyph: ^1.2.0
  test: ^1.16.0

topics:
 - build-runner
