name: build_config
version: 0.4.5
description: Support for parsing `build.yaml` configuration.
repository: https://github.com/dart-lang/build/tree/master/build_config

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  checked_yaml: ^1.0.0
  json_annotation: '>=1.0.0 <5.0.0'
  meta: ^1.1.0
  path: ^1.4.0
  pubspec_parse: ^0.1.5
  yaml: '>=2.1.11 <4.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  term_glyph: ^1.0.0
  test: ^1.6.0

dependency_overrides:
  ## Remove each of the following as they are published
  build:
    path: ../build
  build_daemon:
    path: ../build_daemon
  build_resolvers:
    path: ../build_resolvers
  ## Remove each of the above as they are published
  # Required due to the tight dependency on this package from these packages
  build_runner:
    path: ../build_runner
  build_runner_core:
    path: ../build_runner_core
