name: build_config
version: 0.3.2-dev
description: Support for parsing `build.yaml` configuration.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_config

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: '>=0.12.1 <2.0.0'
  json_annotation: '>=1.0.0 <3.0.0'
  meta: ^1.1.0
  path: ^1.4.0
  pubspec_parse: ^0.1.0
  yaml: ^2.1.11

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.0
  build_vm_compilers: ^0.1.0
  json_serializable: ^2.0.0
  test: ^1.0.0
