name: build_config
version: 0.4.3-dev
description: Support for parsing `build.yaml` configuration.
homepage: https://github.com/dart-lang/build/tree/master/build_config

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  checked_yaml: ^1.0.0
  json_annotation: '>=1.0.0 <4.0.0'
  meta: ^1.1.0
  path: ^1.4.0
  pubspec_parse: ^0.1.5
  yaml: ^2.1.11

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  term_glyph: ^1.0.0
  test: ^1.6.0

dependency_overrides:
  build:
    path: ../build
  build_runner:
    path: ../build_runner
  build_runner_core:
    path: ../build_runner_core
  build_resolvers:
    path: ../build_resolvers
