name: build_config
version: 0.3.0
description: Support for parsing `build.yaml` configuration.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_config

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  build: ^0.12.1
  json_annotation: ^0.2.8
  meta: ^1.1.0
  path: ^1.4.0
  pubspec_parse: ^0.1.0
  yaml: ^2.1.11

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.6
  test: ^0.12.24
