name: build_resolvers
version: 2.4.4-wip
description: Resolve Dart code in a Builder
repository: https://github.com/dart-lang/build/tree/master/build_resolvers
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: '>=6.9.0 <8.0.0'
  async: ^2.5.0
  build: ^2.0.0
  collection: ^1.17.0
  convert: ^3.1.1
  crypto: ^3.0.0
  graphs: '>=1.0.0 <3.0.0'
  logging: ^1.0.0
  package_config: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  pub_semver: ^2.0.0
  stream_transform: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_test: ^2.0.0
  dart_flutter_team_lints: ^3.1.0
  test: ^1.16.0

topics:
 - build-runner
