name: build_resolvers
version: 0.1.0-dev
description: Resolve Dart code in a Builder
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  analyzer: ">=0.27.1 <0.31.0"
  build: ^0.12.0
  cli_util: ^0.1.0
  path: ^1.1.0

dev_dependencies:
  test: ^0.12.0
  build_test: ^0.10.1

dependency_overrides:
  build_test:
    path: ../build_test
