name: build_resolvers
version: 2.0.5-dev
description: Resolve Dart code in a Builder
repository: https://github.com/dart-lang/build/tree/master/build_resolvers

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.1.0
  async: ^2.5.0
  build: ^2.0.0
  crypto: ^3.0.0
  graphs: ">=1.0.0 <3.0.0"
  logging: ^1.0.0
  path: ^1.8.0
  package_config: ^2.0.0
  pool: ^1.5.0
  pub_semver: ^2.0.0
  stream_transform: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  test: ^1.16.0
  build_test: ^2.0.0
