name: build_resolvers
version: 1.3.8-dev
description: Resolve Dart code in a Builder
homepage: https://github.com/dart-lang/build/tree/master/build_resolvers

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.5
  build: ">=1.3.0 <1.4.0"
  crypto: ^2.0.0
  graphs: ^0.2.0
  logging: ^0.11.2
  path: ^1.1.0
  package_config: ^1.9.3
  pub_semver: ^1.3.0
  yaml: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.1
  build_runner: ^1.0.0
  build_vm_compilers: ">=0.1.0 <2.0.0"
  build_modules: any

dependency_overrides:
  build:
    path: ../build
  build_vm_compilers:
    path: ../build_vm_compilers
  build_modules:
    path: ../build_modules
