name: build_resolvers
version: 1.2.2
description: Resolve Dart code in a Builder
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_resolvers

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  analyzer: ^0.39.0
  build: ">=1.1.0 <1.3.0"
  crypto: ^2.0.0
  graphs: ^0.2.0
  logging: ^0.11.2
  package_resolver: ^1.0.0
  path: ^1.1.0
  yaml: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.1
  build_runner: ^1.0.0
  build_vm_compilers: ">=0.1.0 <2.0.0"
  dart_style: any
  build_modules: any

dependency_overrides:
  build_vm_compilers:
    path: ../build_vm_compilers
  build_modules:
    path: ../build_modules
  dart_style:
    git:
      url: git://github.com/dart-lang/dart_style.git
      ref: upgrade-analyzer
