name: build_resolvers
version: 0.3.0
description: Resolve Dart code in a Builder
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_resolvers

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  analyzer: ^0.34.0
  build: ">=2.0.0 <2.1.0"
  path: ^1.1.0

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.1
  build_runner: ^1.0.0
  build_vm_compilers: ^0.1.0

dependency_overrides:
  build:
    path: ../build
