name: example
publish_to: none
environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  analyzer: ">=5.0.0 <10.0.0"
  build: ^4.0.0
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^1.0.0
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.0.0
