name: example
publish_to: none
environment:
  sdk: ^3.3.0

dependencies:
  analyzer: ">=5.0.0 <7.0.0"
  build: ^2.0.0
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.0.0
  dart_flutter_team_lints: ^2.0.0

# TODO: Remove once build_modules version 5.0.6 is published.
dependency_overrides:
  build_modules:
    path: ../build_modules
