name: example
publish_to: none
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ">=2.0.0 <6.0.0"
  build: ^2.0.0
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  dart_flutter_team_lints: ^1.0.0
