name: example

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: ^1.0.0
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^0.3.0

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^1.0.0

dependency_overrides:
  build:
    path: ../build
  build_daemon:
    path: ../build_daemon
  build_resolvers:
    path: ../build_resolvers
  build_runner:
    path: ../build_runner
  build_runner_core:
    path: ../build_runner_core
  build_modules:
    path: ../build_modules
  build_web_compilers:
    path: ../build_web_compilers

  #temp for testing
  analyzer: 0.36.0
