name: _test_common
publish_to: none
description: Test infra for writing build tests. Is not published.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: any
  build_config: any
  build_runner_core: any
  build_test: any
  test_descriptor: ^1.0.0
  test: '>=0.12.42 <2.0.0'

dependency_overrides:
  build:
    path: ../build
  build_config:
    path: ../build_config
  build_resolvers:
    path: ../build_resolvers
  build_runner_core:
    path: ../build_runner_core
  build_test:
    path: ../build_test
