name: _test_common
publish_to: none
description: Test infra for writing build tests. Is not published.
#resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  build: any
  build_config: any
  build_runner_core: any
  build_test: any
  crypto: ^3.0.0
  logging: ^1.0.0
  package_config: ^2.0.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  watcher: ^1.0.0

dependency_overrides:
  build:
    path: ../build
  build_config:
    path: ../build_config
  build_runner_core:
    path: ../build_runner_core
  build_test:
    path: ../build_test
