name: _bazel_codegen
description: Bazel code generation runner
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/bazel_codegen
version: 0.3.4

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  analyzer: ">=0.31.2-alpha.1 <0.34.0"
  args: ^1.4.1
  bazel_worker: ^0.1.2
  build: ">=0.12.7 <2.0.0"
  build_resolvers: ^0.2.1
  glob: ^1.1.0
  logging: ^0.11.3
  path: ^1.4.1
  stack_trace: ^1.7.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.0
  build_vm_compilers: ^0.1.0
  test: ^1.0.0
  test_descriptor: ^1.0.0
