name: build_modules
version: 5.0.4
description: >-
  Builders to analyze and split Dart code into individually compilable modules
  based on imports.
repository: https://github.com/dart-lang/build/tree/master/build_modules

environment:
  sdk: '>=3.0.0 <3.3.0'

dependencies:
  analyzer: '>=5.1.0 <7.0.0'
  async: ^2.5.0
  bazel_worker: ^1.0.0
  build: ^2.0.0
  build_config: ^1.0.0
  collection: ^1.15.0
  crypto: ^3.0.0
  glob: ^2.0.0
  graphs: ^2.0.0
  json_annotation: ^4.3.0
  logging: ^1.0.0
  path: ^1.8.0
  scratch_space: ^1.0.0
  stream_transform: ^2.0.0

dev_dependencies:
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
  # Used inside tests
  build_runner: ^2.0.0
  build_test: ^2.0.0
  dart_flutter_team_lints: ^2.0.0
  json_serializable: ^6.0.0
  test: ^1.16.0
