name: build_modules
version: 3.0.7-dev
description: Builders for Dart modules
repository: https://github.com/dart-lang/build/tree/master/build_modules

environment:
  sdk: ">=2.11.99 <3.0.0"

dependencies:
  analyzer: ^1.0.0
  async: ^2.0.0
  bazel_worker: ">=0.1.20 <2.0.0"
  build: ^2.0.0
  build_config: ">=0.3.0 <0.5.0"
  collection: ^1.0.0
  crypto: ">=2.0.0 <4.0.0"
  glob: ^2.0.0
  graphs: ">=1.0.0 <3.0.0"
  json_annotation: ">=1.2.0 <5.0.0"
  logging: ">=0.11.2 <2.0.0"
  meta: ^1.1.0
  path: ^1.4.2
  pedantic: ^1.0.0
  scratch_space: ">=0.0.4 <2.0.0"
  stream_transform: ^2.0.0

dev_dependencies:
  # Used inside tests
  build_runner: ^1.0.0
  build_test: ^1.0.0
  test: ^1.6.0
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b

dependency_overrides:
  # Remove these when they're published
  build:
    path: ../build
  build_config:
    path: ../build_config
  build_daemon:
    path: ../build_daemon
  build_resolvers:
    path: ../build_resolvers
  build_test:
    path: ../build_test
  build_runner_core:
    path: ../build_runner_core
  build_runner:
    path: ../build_runner
  # Needed to run null safe build tests
  code_builder:
    git: https://github.com/dart-lang/code_builder
