name: build_modules
version: 5.1.4
description: >-
  Builders to analyze and split Dart code into individually compilable modules
  based on imports.
repository: https://github.com/dart-lang/build/tree/master/build_modules
resolution: workspace

environment:
  sdk: '>=3.7.0 <3.12.0-z'

dependencies:
  analyzer: '>=5.1.0 <10.0.0'
  async: ^2.5.0
  bazel_worker: ^1.0.0
  build: '>=2.0.0 <5.0.0'
  collection: ^1.15.0
  crypto: ^3.0.0
  file: ^7.0.1
  glob: ^2.0.0
  graphs: ^2.0.0
  json_annotation: ^4.3.0
  logging: ^1.0.0
  path: ^1.8.0
  scratch_space: ^1.2.0
  stream_transform: ^2.0.0
  uuid: ^4.4.2

dev_dependencies:
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
  build_runner: ^2.0.0
  build_test: ^3.1.0
# TODO(davidmorgan): add back when it's released for build 3.0.0.
#  json_serializable: ^6.9.1
  test: ^1.16.0

topics:
 - build-runner
