name: build_runner
version: 0.3.2-dev
description: Tools to write binaries that run builders.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build

environment:
  sdk: '>=1.22.1 <2.0.0'

dependencies:
  analyzer: ">=0.27.1 <0.30.0"
  build: ^0.9.0
  build_barback: ^0.1.0
  crypto: ">=0.9.2 <3.0.0"
  logging: ^0.11.2
  glob: ^1.1.0
  path: ^1.1.0
  shelf: ^0.6.5
  shelf_static: ^0.2.3
  stack_trace: ^1.6.0
  watcher: ^0.9.7
  yaml: ^2.1.0

dev_dependencies:
  build_test: ^0.6.0
  test: ^0.12.0

dependency_overrides:
  build:
    path: ../build
  build_test:
    path: ../build_test
