name: build_runner
version: 0.8.2-dev
description: Tools to write binaries that run builders.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_runner

environment:
  sdk: '>=2.0.0-dev.37 <2.0.0'

dependencies:
  args: ">=1.4.0 <2.0.0"
  async: ">=1.13.3 <3.0.0"
  build: ^0.12.0
  build_config: ^0.2.5
  build_resolvers: ^0.2.0
  cli_util: ^0.1.2
  code_builder: ">2.3.0 <4.0.0"
  collection: ^1.14.0
  convert: ^2.0.1
  crypto: ">=0.9.2 <3.0.0"
  dart_style: ^1.0.0
  glob: ^1.1.0
  graphs: ^0.1.0
  http_multi_server: ^2.0.0
  io: ^0.3.0
  logging: ^0.11.2
  meta: ^1.1.0
  mime: ^0.9.3
  path: ^1.1.0
  pool: ^1.0.0
  shelf: ">=0.6.5 <0.8.0"
  stack_trace: ^1.9.0
  stream_transform: ^0.0.9
  watcher: ^0.9.7
  yaml: ^2.1.0

dev_dependencies:
  build_test: ^0.10.0
  package_resolver: ^1.0.2
  test: ^0.12.0
  test_descriptor: ^1.0.0
