name: build_runner
version: 2.1.7
description: A build system for Dart code generation and modular compilation.
repository: https://github.com/dart-lang/build/tree/master/build_runner

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  args: ^2.0.0
  async: ^2.5.0
  analyzer: ">=1.4.0 <4.0.0"
  build: ">=2.1.0 <2.3.0"
  build_config: ">=1.0.0 <1.1.0"
  build_daemon: ^3.0.0
  build_resolvers: ^2.0.0
  build_runner_core: ^7.2.0
  code_builder: ^4.0.0
  collection: ^1.15.0
  crypto: ^3.0.0
  dart_style: ^2.0.0
  frontend_server_client: ^2.1.0
  glob: ^2.0.0
  graphs: ^2.0.0
  http_multi_server: ^3.0.0
  io: ^1.0.0
  js: ^0.6.3
  logging: ^1.0.0
  meta: ^1.3.0
  mime: ^1.0.0
  package_config: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  shelf: ^1.0.0
  shelf_web_socket: ^1.0.0
  stack_trace: ^1.10.0
  stream_transform: ^2.0.0
  timing: ^1.0.0
  watcher: ^1.0.0
  web_socket_channel: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
  stream_channel: ^2.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
  _test_common:
    path: ../_test_common
