name: build_runner
version: 2.4.16-wip
description: A build system for Dart code generation and modular compilation.
repository: https://github.com/dart-lang/build/tree/master/build_runner
resolution: workspace

environment:
  sdk: ^3.7.0

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: '>=4.4.0 <8.0.0'
  args: ^2.0.0
  async: ^2.5.0
  build: ^2.3.4-wip
  build_config: ">=1.1.0 <1.2.0"
  build_daemon: ^4.0.0
  build_resolvers: ^2.4.4
  build_runner_core: ^9.0.0-wip
  code_builder: ^4.2.0
  collection: ^1.15.0
  crypto: ^3.0.0
  dart_style: '>=2.3.7 <4.0.0'
  frontend_server_client: ">=3.0.0 <5.0.0"
  glob: ^2.0.0
  graphs: ^2.2.0
  http: ^1.2.2
  http_multi_server: ^3.0.0
  io: ^1.0.0
  js: '>=0.6.3 <0.8.0'
  logging: ^1.0.0
  meta: ^1.3.0
  mime: '>=1.0.0 <3.0.0'
  package_config: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  shelf: ^1.0.0
  shelf_web_socket: ">=1.0.0 <4.0.0"
  stack_trace: ^1.10.0
  stream_transform: ^2.0.0
  timing: ^1.0.0
  watcher: ^1.0.0
  web: ^1.1.0
  web_socket_channel: ">=2.3.0 <4.0.0"
  yaml: ^3.0.0

dev_dependencies:
  _test_common:
    path: ../_test_common
  build_test: ^3.0.0-wip
  build_web_compilers: ^4.0.0
  dart_flutter_team_lints: ^3.1.0
  stream_channel: ^2.0.0
  test: ^1.25.5
  test_descriptor: ^2.0.0
  test_process: ^2.0.0

topics:
 - build-runner
