name: build_runner
version: 2.11.0-wip
description: A build system for Dart code generation and modular compilation.
repository: https://github.com/dart-lang/build/tree/master/build_runner
resolution: workspace

environment:
  sdk: ^3.7.0

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: '>=8.0.0 <10.0.0'
  args: ^2.5.0
  async: ^2.5.0
  build: ^4.0.0
  build_config: ">=1.2.0 <1.3.0"
  build_daemon: ^4.0.0
  built_collection: ^5.1.1
  built_value: ^8.10.1
  code_builder: ^4.2.0
  collection: ^1.15.0
  convert: ^3.0.0
  crypto: ^3.0.0
  dart_style: '>=2.3.7 <4.0.0'
  glob: ^2.0.0
  graphs: ^2.2.0
  http_multi_server: ^3.0.0
  io: ^1.0.0
  json_annotation: ^4.8.1
  logging: ^1.0.0
  meta: ^1.16.0
  mime: '>=1.0.0 <3.0.0'
  package_config: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  pub_semver: ^2.0.0
  shelf: ^1.0.0
  shelf_web_socket: ">=1.0.0 <4.0.0"
  stream_transform: ^2.0.0
  watcher: ^1.0.0
  web_socket_channel: ">=2.3.0 <4.0.0"
  yaml: ^3.0.0

dev_dependencies:
  build_test: ^3.0.0
  dart_flutter_team_lints: ^3.1.0
  stream_channel: ^2.0.0
  test: ^1.25.5
  test_descriptor: ^2.0.0

topics:
 - build-runner

dependency_overrides:
  watcher:
    git:
      url: https://github.com/dart-lang/tools
      ref: 97014f33a2aad59385df73f25baf9c304ca5c866
      path: pkgs/watcher
