name: build_runner
version: 0.6.0-dev
description: Tools to write binaries that run builders.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build

environment:
  sdk: '>=1.22.1 <2.0.0'

dependencies:
  analyzer: ">=0.27.1 <0.31.0"
  args: ">=0.13.7 <2.0.0"
  async: ">=1.13.3 <3.0.0"
  build: ^0.10.1
  build_barback: ^0.4.0
  crypto: ">=0.9.2 <3.0.0"
  glob: ^1.1.0
  logging: ^0.11.2
  path: ^1.1.0
  shelf: ">=0.6.5 <0.8.0"
  mime: ^0.9.3
  stack_trace: ^1.6.0
  stream_transform: ^0.0.9
  watcher: ^0.9.7
  yaml: ^2.1.0

dependency_overrides:
  build:
    path: ../build
  build_test:
    path: ../build_test

dev_dependencies:
  build_test: ^0.8.0
  cli_util: ^0.1.2
  dart_style: ^1.0.0
  test: ^0.12.0
  test_descriptor: ^1.0.0
