name: build_runner
version: 1.7.1
description: Tools to write binaries that run builders.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_runner

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  args: ">=1.4.0 <2.0.0"
  async: ">=1.13.3 <3.0.0"
  build: ">=1.0.0 <1.3.0"
  build_config: ">=0.4.1 <0.4.2"
  build_daemon: ^2.1.0
  build_resolvers: "^1.0.0"
  build_runner_core: ^4.0.0
  code_builder: ">2.3.0 <4.0.0"
  collection: ^1.14.0
  crypto: ">=0.9.2 <3.0.0"
  dart_style: ^1.0.0
  glob: ^1.1.0
  graphs: ^0.2.0
  http_multi_server: ^2.1.0
  io: ^0.3.0
  js: ^0.6.1+1
  logging: ^0.11.2
  meta: ^1.1.0
  mime: ^0.9.3+3
  path: ^1.1.0
  pedantic: ^1.0.0
  pool: ^1.0.0
  pub_semver: ^1.4.0
  pubspec_parse: ^0.1.0
  shelf: ">=0.6.5 <0.8.0"
  shelf_web_socket: ^0.2.2+4
  stack_trace: ^1.9.0
  stream_transform: ^0.0.9
  timing: ^0.1.1
  watcher: ^0.9.7
  web_socket_channel: ^1.0.9
  yaml: ^2.1.0

dev_dependencies:
  build_test: ^0.10.0
  build_web_compilers: ^2.0.0
  mockito: ^4.0.0
  package_resolver: ^1.0.2
  stream_channel: ">=1.6.0 <3.0.0"
  test: ^1.3.3
  test_descriptor: ^1.0.0
  test_process: ^1.0.0
  _test_common:
    path: ../_test_common
