name: build_daemon
version:  4.0.5-wip
description: A daemon for running Dart builds.
repository: https://github.com/dart-lang/build/tree/master/build_daemon
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.1.0
  crypto: ^3.0.3
  http_multi_server: ^3.0.0
  logging: ^1.0.0
  path: ^1.8.0
  pool: ^1.5.0
  shelf: ^1.0.0
  shelf_web_socket: ">=1.0.0 <4.0.0"
  stream_transform: ^2.0.0
  watcher: ^1.0.0
  web_socket_channel: ">=2.3.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.0.0
  built_value_generator: ^8.1.0
  mockito: ^5.0.0
  test: ^1.25.5
  test_descriptor: ^2.0.0

topics:
 - build-runner
