name: build_daemon
version:  3.0.2
description: A daemon for running Dart builds.
repository: https://github.com/dart-lang/build/tree/master/build_daemon

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  http_multi_server: ^3.0.0
  logging: ^1.0.0
  path: ^1.8.0
  pool: ^1.5.0
  shelf: ^1.0.0
  shelf_web_socket: ^1.0.0
  stream_transform: ^2.0.0
  watcher: ^1.0.0
  web_socket_channel: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  # TODO: untangle analyzer dependency
  built_value_generator: ^8.0.0
  lints: ^1.0.0
  mockito: ^5.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  uuid: ^3.0.0
