name: build_daemon
version: 2.1.0
description: A daemon for running Dart builds.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_daemon

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_collection: ^4.1.0
  built_value: ^6.3.0
  http_multi_server: ^2.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0
  package_resolver: ^1.0.6
  path: ^1.6.2
  pool: ^1.3.6
  shelf: ^0.7.4
  shelf_web_socket: ^0.2.2+4
  stream_transform: ^0.0.14+1
  watcher: ^0.9.7
  web_socket_channel: ^1.0.9

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.2.0
  mockito: ^4.0.0
  test: ^1.3.3
  test_descriptor: ^1.1.1
  uuid: ^2.0.0
