name: source_gen
version: 0.9.7+1
description: >-
  Source code generation builders and utilities for the Dart build system
homepage: https://github.com/dart-lang/source_gen

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: '>=0.39.11 <0.41.0'
  async: ^2.0.7
  build: ^1.0.0
  dart_style: ^1.0.0
  glob: ^1.1.0
  meta: ^1.1.0
  path: ^1.3.2
  pedantic: ^1.0.0
  source_span: ^1.4.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^1.0.0
  test: ^1.0.0
  _test_annotations:
    path: ../_test_annotations
