name: source_gen
version: 1.2.0
description: >-
  Source code generation builders and utilities for the Dart build system
repository: https://github.com/dart-lang/source_gen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.1.0
  async: ^2.5.0
  build: ^2.1.0
  dart_style: ^2.0.0
  glob: ^2.0.0
  meta: ^1.3.0
  path: ^1.8.0
  source_span: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  _test_annotations:
    path: ../_test_annotations
  build_test: ^2.0.0
  term_glyph: ^1.2.0
  test: ^1.16.0
