publish_to: none
name: build_development_tools
description: Collection of scripts used during development of build packages.

environment:
  sdk: ^3.5.0-259.0.dev

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  yaml_edit: ^2.0.1

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  test: ^1.20.1
  test_descriptor: ^2.0.0
