publish_to: none
name: build_development_tools
description: Collection of scripts used during development of build packages.

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml_edit: ^2.0.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test_descriptor: ^2.0.0
  test: ^1.20.1
