name: build_compilers
version: 0.1.1-dev
description: Builder implementations wrapping Dart compilers.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build

environment:
  sdk: '>=1.22.1 <2.0.0'

dependencies:
  analyzer: ^0.30.0
  bazel_worker: ^0.1.4
  build: ^0.12.0
  cli_util: ^0.1.2
  json_annotation: ^0.2.0
  logging: ^0.11.2
  path: ^1.4.2
  scratch_space: ^0.0.1

dev_dependencies:
  build_runner: ^0.6.0
  build_test: ^0.9.0
  json_serializable: ^0.2.4
  source_gen: ^0.7.0
  test: ^0.12.24
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b

dependency_overrides:
  build:
    path: ../build
  build_test:
    path: ../build_test
