name: e2e_example
version: 0.2.0

environment:
  sdk: '>=1.9.1 <2.0.0'

dependencies:
  build: ^0.7.0
  build_barback: ^0.1.0

dev_dependencies:
  build_runner: ^0.3.0

transformers:
- e2e_example:
    $include: 'web/*.txt'
