name: build_test
description: Utilities for writing unit tests of Builders.
version: 1.4.0-dev
homepage: https://github.com/dart-lang/build/tree/master/build_test

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  async: "^2.5.0"
  build: "^2.0.0-dev"
  build_config: ">=0.2.0 <0.5.0"
  build_resolvers: ^2.0.0
  crypto: "^3.0.0"
  glob: "^2.0.0"
  html: "^0.15.0"
  logging: "^1.0.0"
  matcher: ^0.12.0
  package_config: '^2.0.0'
  path: ^1.8.0
  pedantic: ^1.10.0
  stream_transform: "^2.0.0"
  test: '^1.16.0'
  test_core: '>=0.3.12 <0.4.0'
  watcher: '^1.0.0'

dev_dependencies:
  analyzer: ^1.0.0
  collection: ^1.14.0

dependency_overrides:
  # Remove this once the respective packages are published
  build:
    path: ../build
  build_resolvers:
    path: ../build_resolvers
  graphs:
    git:
      url: https://github.com/hovadur/graphs.git
      ref: a19da5b30388752a62d0eb96d38f371311c0cebf
