name: build_test
description: Utilities for writing unit tests of Builders.
version: 0.2.0
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build

dependencies:
  build: ^0.4.0
  logging: ^0.11.2
  test: ^0.12.0
  watcher: ^0.9.7

environment:
  sdk: ">=1.8.0 <2.0.0"
