name: build_test
description: Utilities for writing unit tests of Builders.
version: 0.10.2+4
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_test

environment:
  sdk: '>=2.0.0-dev.32 <2.0.0'

dependencies:
  async: ">=1.2.0 <3.0.0"
  build: ^0.12.0
  build_config: ">=0.2.0 <0.4.0"
  build_resolvers: ^0.2.0
  collection: ^1.14.0
  stream_transform: ^0.0.11
  crypto: ">=0.9.2 <3.0.0"
  glob: ^1.1.0
  html: ">=0.9.0 <=0.14.0"
  logging: ^0.11.2
  matcher: ^0.12.0
  package_resolver: ^1.0.2
  path: ^1.4.1
  test: ^0.12.36
  watcher: ^0.9.7

dev_dependencies:
  analyzer: ">=0.27.1 <0.33.0"
