name: build_test
description: Utilities for writing unit tests of Builders.
version: 2.2.4-wip
repository: https://github.com/dart-lang/build/tree/master/build_test
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  async: ^2.5.0
  build: ^2.1.0
  build_config: ^1.0.0
  build_resolvers: ^2.4.0
  crypto: ^3.0.0
  glob: ^2.0.0
  html: ^0.15.0
  logging: ^1.0.0
  matcher: ^0.12.0
  package_config: ^2.0.0
  path: ^1.8.0
  stream_transform: ^2.0.0
  test: ^1.16.0
  test_core: '>=0.3.19 <0.7.0'
  watcher: ^1.0.0

dev_dependencies:
  analyzer: '>=5.2.0 <8.0.0'
  collection: ^1.15.0

topics:
 - build-runner
 - testing
