name: build_test
description: Utilities for writing unit tests of Builders.
version: 1.3.7-dev
homepage: https://github.com/dart-lang/build/tree/master/build_test

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  async: ">=1.2.0 <3.0.0"
  build: ">=1.6.0 <1.7.0"
  build_config: ">=0.2.0 <0.5.0"
  build_resolvers: ^1.3.5
  crypto: ">=0.9.2 <4.0.0"
  glob: ^2.0.0
  html: ">=0.9.0 <0.16.0"
  logging: ">=0.11.2 <2.0.0"
  matcher: ^0.12.0
  package_config: '>=1.9.0 <3.0.0'
  path: ^1.4.1
  pedantic: ^1.0.0
  stream_transform: ">=0.0.20 <3.0.0"
  test: '>=0.12.42 <2.0.0'
  test_core: '>=0.3.6 <0.4.0'
  watcher: '>=0.9.7 <2.0.0'

dev_dependencies:
  analyzer: ">=0.35.4 <0.42.0"
  collection: ^1.14.0

dependency_overrides:
  ## Remove each of the below as they are published
  build:
    path: ../build
  build_config:
    path: ../build_config
  build_resolvers:
    path: ../build_resolvers
  ## Remove each of the above as they are published