name: source_gen
version: 0.7.1-dev
author: Dart Team <misc@dartlang.org>
description: Automated source code generation for Dart.
homepage: https://github.com/dart-lang/source_gen
environment:
  sdk: '>=1.22.1 <2.0.0'
dependencies:
  analyzer: '>=0.29.10 <0.31.0'
  build: ^0.9.0
  dart_style: '>=0.1.7 <2.0.0'
  meta: ^1.1.0
  path: ^1.3.2
  source_span: ^1.4.0
dev_dependencies:
  build_test: ^0.6.0
  collection: ^1.1.2
  cli_util: '>=0.1.0 <0.2.0'
  logging: ^0.11.3
  test: ^0.12.3
  _test_annotations:
    path: ./_test_annotations
