name: build_runner_core
version: 6.1.5
description: Core tools to write binaries that run builders.
repository: https://github.com/dart-lang/build/tree/master/build_runner_core

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  async: ">=1.13.3 <3.0.0"
  build: ">=1.5.1 <1.7.0"
  build_config: '>=0.4.3 <0.4.6'
  build_resolvers: ^1.4.0
  collection: ^1.14.0
  convert: ^2.0.1
  crypto: ">=0.9.2 <3.0.0"
  glob: ^1.1.0
  graphs: ^0.2.0
  json_annotation: '>=1.0.0 <5.0.0'
  logging: ^0.11.2
  meta: ^1.1.0
  path: ^1.1.0
  package_config: ^1.9.0
  pedantic: ^1.0.0
  pool: ^1.0.0
  timing: ^0.1.1
  watcher: ^0.9.7
  yaml: '>=2.1.11 <4.0.0'

dev_dependencies:
  build_test: ^1.0.0
  test: ^1.0.0
  test_descriptor: ^1.0.0
  test_process: ^1.0.0
  _test_common:
    path: ../_test_common
