name: build_runner_core
version: 7.2.3
description: Core tools to write binaries that run builders.
repository: https://github.com/dart-lang/build/tree/master/build_runner_core

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  async: ^2.5.0
  build: ^2.1.0
  build_config: ^1.0.0
  build_resolvers: ^2.0.0
  collection: ^1.15.0
  convert: ^3.0.0
  crypto: ^3.0.0
  glob: ^2.0.0
  graphs: ^2.0.0
  json_annotation: ^4.3.0
  logging: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0
  package_config: ^2.0.0
  pool: ^1.5.0
  timing: ^1.0.0
  watcher: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  analyzer: ">=2.0.0 <4.0.0"
  build_runner: ^2.0.0
  build_test: ^2.0.0
  lints: ^1.0.0
  json_serializable: ^6.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
  _test_common:
    path: ../_test_common
