name: build_runner_core
version: 9.0.0-wip
description: Core tools to organize the structure of a build and run Builders.
repository: https://github.com/dart-lang/build/tree/master/build_runner_core
resolution: workspace

environment:
  sdk: ^3.7.0

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: '>=6.9.0 <8.0.0'
  async: ^2.5.0
  build: ^2.4.3-wip
  build_config: ^1.0.0
  build_resolvers: ^2.4.0
  built_collection: ^5.1.1
  built_value: ^8.9.5
  collection: ^1.15.0
  convert: ^3.0.0
  crypto: ^3.0.0
  glob: ^2.0.0
  graphs: ^2.0.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.3.0
  package_config: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  timing: ^1.0.0
  watcher: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  _test_common:
    path: ../_test_common
  build_runner: ^2.0.0
  build_test: ^3.0.0-wip
  built_value_generator: ^8.9.5
  dart_flutter_team_lints: ^3.1.0
  json_serializable: ^6.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0

topics:
 - build-runner
