name: build_runner_core
version: 8.0.0
description: Core tools to organize the structure of a build and run Builders.
repository: https://github.com/dart-lang/build/tree/master/build_runner_core

# This package can't be part of the workspace because it requires a very recent
# Dart SDK - see the top-level pubspec for details.
resolution: workspace

environment:
  sdk: ^3.6.0

platforms:
  linux:
  windows:
  macos:

dependencies:
  async: ^2.5.0
  build: ^2.4.0
  build_config: ^1.0.0
  build_resolvers: ^2.4.0
  collection: ^1.15.0
  convert: ^3.0.0
  crypto: ^3.0.0
  glob: ^2.0.0
  graphs: ^2.0.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.3.0
  package_config: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  timing: ^1.0.0
  watcher: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  _test_common:
    path: ../_test_common
  analyzer: '>=6.9.0 <8.0.0'
  build_runner: ^2.0.0
  build_test: ^2.0.0
  dart_flutter_team_lints: ^3.1.0
  json_serializable: ^6.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0

topics:
 - build-runner
