name: scratch_space
version: 1.0.3-wip
description: A tool to manage running external executables within package:build.
repository: https://github.com/dart-lang/build/tree/master/scratch_space

topics:
  - build-runner
  - codegen

environment:
  sdk: ^3.3.0

dependencies:
  build: ^2.0.0
  crypto: ^3.0.0
  path: ^1.8.0
  pool: ^1.5.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  dart_flutter_team_lints: ^2.0.0
  test: ^1.16.0
