name: source_gen_example_usage

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.10.3
  build_verify: ^2.0.0
  source_gen_example:
    path: ../example
  test: ^1.5.1

dependency_overrides:
  source_gen:
    path: ../source_gen
