# This file only exists to enable the top level shared analysis_options.yaml
# file to import package:dart_flutter_team_lints.
name: _for_analysis_options_only
publish_to: none
resolution: workspace
environment:
  sdk: ^3.5.0-0
dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
