# Created with package:mono_repo v3.1.0-beta.3
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: latest
      - run: dart --version
      - uses: actions/checkout@v2
      - run: pub global activate mono_repo 3.1.0-beta.3
      - run: pub global run mono_repo generate --validate
  job_002:
    name: "OS: linux; SDK: dev; PKGS: _test, _test_common, _test_null_safety; TASKS: `dartanalyzer --fatal-infos --fatal-warnings .`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test _test_common _test_null_safety
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh dartanalyzer_0
  job_003:
    name: "OS: linux; SDK: dev; PKG: _test; TASKS: [`pub run build_runner test -- -p chrome --test-randomize-ordering-seed=random`, `pub run build_runner test -- -p vm test/configurable_uri_test.dart --test-randomize-ordering-seed=random`]"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh command_0 command_1
  job_004:
    name: "OS: windows; SDK: dev; PKG: _test; TASKS: [`pub run build_runner test -- -p chrome --test-randomize-ordering-seed=random`, `pub run build_runner test -- -p vm test/configurable_uri_test.dart --test-randomize-ordering-seed=random`]"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh command_0 command_1
  job_005:
    name: "OS: linux; SDK: dev; PKG: _test; TASKS: `pub run test --total-shards 3 --shard-index 0 --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_00
  job_006:
    name: "OS: linux; SDK: dev; PKG: _test; TASKS: `pub run test --total-shards 3 --shard-index 1 --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_01
  job_007:
    name: "OS: linux; SDK: dev; PKG: _test; TASKS: `pub run test --total-shards 3 --shard-index 2 --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_02
  job_008:
    name: "OS: windows; SDK: dev; PKG: _test; TASKS: `pub run test --total-shards 3 --shard-index 0 --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_00
  job_009:
    name: "OS: windows; SDK: dev; PKG: _test; TASKS: `pub run test --total-shards 3 --shard-index 1 --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_01
  job_010:
    name: "OS: windows; SDK: dev; PKG: _test; TASKS: `pub run test --total-shards 3 --shard-index 2 --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_02
  job_011:
    name: "OS: windows; SDK: dev; PKG: _test_null_safety; TASKS: `dartanalyzer --fatal-infos --fatal-warnings .`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test_null_safety
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh dartanalyzer_0
  job_012:
    name: "OS: linux; SDK: dev; PKG: _test_null_safety; TASKS: [`pub run build_runner test -- -p chrome,vm --test-randomize-ordering-seed=random`, `pub run build_runner test --define=\"build_web_compilers:entrypoint=compiler=dart2js\" -- -p chrome --test-randomize-ordering-seed=random`]"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test_null_safety
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh command_2 command_3
  job_013:
    name: "OS: windows; SDK: dev; PKG: _test_null_safety; TASKS: [`pub run build_runner test -- -p chrome,vm --test-randomize-ordering-seed=random`, `pub run build_runner test --define=\"build_web_compilers:entrypoint=compiler=dart2js\" -- -p chrome --test-randomize-ordering-seed=random`]"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: _test_null_safety
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh command_2 command_3
  job_014:
    name: "OS: linux; SDK: dev; PKGS: build, build_config, build_daemon, build_modules, build_resolvers, build_runner, build_runner_core, build_test, build_vm_compilers, build_web_compilers, example, scratch_space; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos --fatal-warnings .`]"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build build_config build_daemon build_modules build_resolvers build_runner build_runner_core build_test build_vm_compilers build_web_compilers example scratch_space
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh dartfmt dartanalyzer_0
  job_015:
    name: "OS: linux; SDK: 2.9.0; PKGS: build, build_config, build_daemon, build_resolvers, build_runner_core, build_test, build_vm_compilers, scratch_space; TASKS: `dartanalyzer --fatal-warnings .`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.9.0"
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build build_config build_daemon build_resolvers build_runner_core build_test build_vm_compilers scratch_space
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh dartanalyzer_1
  job_016:
    name: "OS: linux; SDK: dev; PKG: build; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_04
  job_017:
    name: "OS: linux; SDK: dev; PKG: build_config; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_config
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_04
  job_018:
    name: "OS: linux; SDK: dev; PKG: build_daemon; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_daemon
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_04
  job_019:
    name: "OS: linux; SDK: dev; PKG: build_resolvers; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_resolvers
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_04
  job_020:
    name: "OS: linux; SDK: dev; PKG: build_runner_core; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner_core
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_04
  job_021:
    name: "OS: linux; SDK: dev; PKG: build_test; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_test
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_04
  job_022:
    name: "OS: linux; SDK: dev; PKG: build_web_compilers; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_web_compilers
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_04
  job_023:
    name: "OS: linux; SDK: dev; PKG: scratch_space; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: scratch_space
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_04
  job_024:
    name: "OS: windows; SDK: dev; PKG: build; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_04
  job_025:
    name: "OS: windows; SDK: dev; PKG: build_config; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_config
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_04
  job_026:
    name: "OS: windows; SDK: dev; PKG: build_daemon; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_daemon
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_04
  job_027:
    name: "OS: windows; SDK: dev; PKG: build_resolvers; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_resolvers
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_04
  job_028:
    name: "OS: windows; SDK: dev; PKG: build_runner_core; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner_core
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_04
  job_029:
    name: "OS: windows; SDK: dev; PKG: build_test; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_test
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_04
  job_030:
    name: "OS: windows; SDK: dev; PKG: build_web_compilers; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_web_compilers
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_04
  job_031:
    name: "OS: windows; SDK: dev; PKG: scratch_space; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: scratch_space
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_04
  job_032:
    name: "OS: linux; SDK: dev; PKG: build_modules; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_modules
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_05
  job_033:
    name: "OS: windows; SDK: dev; PKG: build_modules; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_modules
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_05
  job_034:
    name: "OS: linux; SDK: dev; PKG: build_runner; TASKS: `pub run test -x integration --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_06
  job_035:
    name: "OS: linux; SDK: dev; PKG: build_runner; TASKS: `pub run test -t integration --total-shards 5 --shard-index 0 --test-randomize-ordering-seed=random --no-chain-stack-traces`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_07
  job_036:
    name: "OS: linux; SDK: dev; PKG: build_runner; TASKS: `pub run test -t integration --total-shards 5 --shard-index 1 --test-randomize-ordering-seed=random --no-chain-stack-traces`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_08
  job_037:
    name: "OS: linux; SDK: dev; PKG: build_runner; TASKS: `pub run test -t integration --total-shards 5 --shard-index 2 --test-randomize-ordering-seed=random --no-chain-stack-traces`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_09
  job_038:
    name: "OS: linux; SDK: dev; PKG: build_runner; TASKS: `pub run test -t integration --total-shards 5 --shard-index 3 --test-randomize-ordering-seed=random --no-chain-stack-traces`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_10
  job_039:
    name: "OS: linux; SDK: dev; PKG: build_runner; TASKS: `pub run test -t integration --total-shards 5 --shard-index 4 --test-randomize-ordering-seed=random --no-chain-stack-traces`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_11
  job_040:
    name: "OS: linux; SDK: 2.9.0; PKG: build_runner_core; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.9.0"
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner_core
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_04
  job_041:
    name: "OS: windows; SDK: 2.9.0; PKG: build_runner_core; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.9.0"
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_runner_core
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_04
  job_042:
    name: "OS: linux; SDK: dev; PKG: build_vm_compilers; TASKS: `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_vm_compilers
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh test_03
  job_043:
    name: "OS: windows; SDK: dev; PKG: build_vm_compilers; TASKS: `pub run test`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: build_vm_compilers
          TRAVIS_OS_NAME: windows
        run: tool/ci.sh test_03
