name: build_vm_compilers
version: 1.0.5-dev
description: Builder implementations wrapping Dart VM compilers.
homepage: https://github.com/dart-lang/build/tree/master/build_vm_compilers

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ">=0.35.0 <0.40.0"
  build: ^1.0.0
  build_config: ">=0.3.0 <0.5.0"
  build_modules: ^2.0.0
  path: ^1.6.0
  pool: ^1.3.0

dev_dependencies:
  build_runner: ^1.0.0
  test: ^1.0.0
  test_descriptor: ^1.1.0
  _test_common:
    path: ../_test_common

dependency_overrides:
  build:
    path: ../build
  build_resolvers:
    path: ../build_resolvers
  build_runner:
    path: ../build_runner
  build_runner_core:
    path: ../build_runner_core