name: build_vm_compilers
version: 1.0.10
description: Builder implementations wrapping Dart VM compilers.
repository: https://github.com/dart-lang/build/tree/master/build_vm_compilers

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ">=1.0.0 <4.0.0"
  build: ^2.0.0
  build_config: ^1.0.0
  build_modules: ^4.0.0
  path: ^1.8.0
  pool: ^1.5.0

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  _test_common:
    path: ../_test_common
